# Generated by Django 4.2.7 on 2023-12-19 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import validationApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('validationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=50)),
                ('plate_number', models.CharField(default='', max_length=10, validators=[validationApp.models.Vehicle.validate_plate_number])),
                ('manufacture_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must contain UR (ur.ac.rw)', regex='.*ur\\.ac\\.rw.*')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[validationApp.models.Participant.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='participant',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='validationApp.vehicle'),
        ),
    ]
