# Generated by Django 4.2.7 on 2023-12-19 15:25

from django.db import migrations, models
import django.db.models.deletion
import validationApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('validationApp', '0002_vehicle_alter_participant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='participant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='validationApp.participant'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_date',
            field=models.DateField(validators=[validationApp.models.Vehicle.validate_date_of_vehicles]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='', max_length=7, validators=[validationApp.models.Vehicle.validate_plate_number]),
        ),
    ]
