# Generated by Django 4.2.7 on 2023-12-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validationApp', '0003_remove_participant_vehicle_vehicle_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='participant',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='validationApp.participant'),
        ),
    ]
